run the sequence in DB 

to generate Id loke OD1,OD2...
OD prefix comes from java class by hard coding
1,2,3 sequence can be generated by running squence for a class AT database side


Creating squence

create sequence ORDER-ID-SEQ
STATRS WITH 1
INCREMENT BY 1;